### ISSUE TITLE
SafeStrNCpy not so safe

### ISSUE THREAD

**Issue by williamcroberts** [01org/tpm2.0-tools#124]
The SafeStrNCopy function here: https://github.com/01org/tpm2.0-tools/blob/master/src/common.h#L82
is not so safe. strncpy can be used when strings don't contain null bytes if len is within the allocated region. The first thing this routine does is call strlen(src) > 0, which isn't safe, since it's not bounded by len.

**Comment by williamcroberts** [comment]
As pointed out by others, there is also an issue on n-1 when n == 0

**Comment by flihp** [comment]
I ran into this while porting a command over to use the new common options stuff. I went the route of using strncpy (with `n` set to destination buffer length - 1) instead of snprintf. Using snprintf hadn't occurred to me but like it. I hadn't realized that strncpy will `\0` pad the whole of the destination buffer if the source string is shorter.

Good fix.

**Comment by williamcroberts** [comment]
strncpy() also doesn't guarantee null terminated, that's the major issue. I've never seen an strncpy() implementation that zeros all the end of the destination buffer on source being shorter.
