### ISSUE TITLE
tpm2_getrandom -s option expects <bitsRequested> and not <bytesRequested>

### ISSUE THREAD

**Issue by danglus** [01org/tpm2.0-tools#251]
What should be fixed? the implementation or the help ?
 additionally, the -o option seems to be mandatory and not optional.

------------------

root@optn36:~/tpm/tpm2.0-tools/test# tpm2_getrandom -h

tpm2_getrandom  [options]
Usage: tpm2_getrandom  [-h/--help]
   or: tpm2_getrandom [-v/--version]
   or: tpm2_getrandom [-s/--size <bytesRequested>] [-o/--of <outfilename>]
   or: tpm2_getrandom  [-s/--size <bytesRequested>] [-o/--of <outfilename>]
                      [-i/--ip <ipAddress>] [-p/--port <port>] [-d/--dbg <dbgLevel>]

where:

   -h/--help                       display this help and exit.
   -v/--version                    display version information and exit.
   -s/--size <bytesRequested>      specifies the size of the bytesRequested.
   -o/--of <outfilename>           specifies the filename of output:
   -p/--port <port>                specifies the port number (default:2323).
   -d/--dbg <dbgLevel>             specifies level of debug messages:
                                     0 (high level test results)
                                     1 (test app send/receive byte streams)
                                     2 (resource manager send/receive byte streams)
                                     3 (resource manager tables)

example:
   tpm2_getrandom -s 20 -o random.out
root@optn36:~/tpm/tpm2.0-tools/test# tpm2_getrandom -s 256
Argument mismatched!
Please type "tpm2_getrandom -h" get the usage!
root@optn36:~/tpm/tpm2.0-tools/test# tpm2_getrandom -s 256 -o out.random

GetRandom succ...
byte size: 32
 0xA4 0xB2 0xA6 0xF3 0x4F 0x01 0x84 0xA0 0x10 0xE7 0x53 0x61 0x1A 0xCF 0x65 0x8F 0x4A 0x42 0x55 0x23 0xC6 0xC6 0x4B 0x51 0x55 0xE9 0xAE 0xDB 0x1A 0xDA 0x98 0x2D

**Comment by williamcroberts** [comment]
-s expects bytes, I am not sure why your saying bits, or if I am misunderstanding. It looks like the output could be cleaned up and -o made optional. -s could likely be made a positional argument as well since it is required. The output file's stat size is the same as the byte's requested size.

$ ./tpm2_getrandom -s 8 -o foo
byte size: 8
 0x6E 0x3A 0x7D 0x3E 0x85 0x74 0x96 0x49
$ stat foo
  File: 'foo'
  Size: 8         	Blocks: 8          IO Block: 4096   regular file
Device: fc00h/64512d	Inode: 16521139    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( x/x)   Gid: ( x/x)
Access: 2017-03-15 11:27:19.360442645 -0700
Modify: 2017-03-15 11:27:19.360442645 -0700
Change: 2017-03-15 11:27:19.360442645 -0700
 Birth: -

**Comment by williamcroberts** [comment]
See PR #256

**Comment by williamcroberts** [comment]
@danglus can you look at PR #256 and let me know if this is what you wanted?

**Comment by williamcroberts** [comment]
-s is now a positional argument for tpm2_getrandom and it always used bytes requested not bits.
