### ISSUE TITLE
failed to initialize TCTI context 0x01 

### ISSUE THREAD

**Issue by oscarcreativeshop** [01org/tpm2.0-tools#292]
I get this error after updating tools to new commit. any suggestions?

**Comment by williamcroberts** [comment]
There has been a bit of a disruptive change. The new resource manager, tabrmd is the default. The TSS has had the old resourcemanager scraped on master, and a 1.x branch has been created to preserve the older resourcemanager.

https://github.com/01org/TPM2.0-TSS
https://github.com/01org/tpm2-abrmd

Your options are twofold:
1. Update to tabrmd
2. Use the old resource manager via --tcti=socket option.

Granted, with that said... the old way seems broken and hanging on recvfrom. I used the 1.0 tag from the TSS.

```
$ ./tpm2_takeownership -c --tcti=socket
Failed to initialize tcti context: 0x1
```
Strace:
```
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 4
connect(3, {sa_family=AF_INET, sin_port=htons(2322), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
connect(4, {sa_family=AF_INET, sin_port=htons(2321), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
sendto(3, "\0\0\0\1", 4, MSG_NOSIGNAL, NULL, 0) = 4
recvfrom(3, 
```

**Comment by williamcroberts** [comment]
@flihp care to comment?

**Comment by flihp** [comment]
I'll give this a test in a bit. The CI stuff running the tabrmd TCTI by default now. I guess this means that the socket / simulator TCTI isn't getting exercised by the CI so maybe the right thing to do is to do two runs of the test scripts (one against the tabrmd, the other against the simulator directly). I'll look into setting this up since it should (hopefully) trigger the issue you're seeing above.

**Comment by flihp** [comment]
So I can't repro this but, naturally, I found a different issue :) What I found is that when using the socket TCTI to talk directly to the simulator the tools don't send the simulator the 'startup' command. This was something that the resourcemgr did for us, and the tabrmd does this as well. We've already got a tool that does this (tpm2_startup) but it may be something we want the tools to do by default (this is your call @williamcroberts).

Anyways back to the issue at hand:
I've attempted to setup a build as close to what you've described as possible: TSS from the 1.0 tag, tools from master. Running `tpm2_takeownership -c --tcti=socket` in this configuration directly against the simulator returns RC 0x100 which is `TPM_RC_INITIALIZE`. This is the RC you get when the TPM hasn't been initialized (haven't yet run the startup command). If I then run `tpm2_startup -c --tcti=socket` it completes successfully. I'm then able to run `tpm2_takeownership -c --tcti=socket' as expected.

This disagrees with your experiences above so I'm not sure what to do next. Since you're both seeing the same behavior it's probably something on my end. Not sure what though. Ideas?

**Comment by williamcroberts** [comment]
@flihp is the startup command simulator specific?

**Comment by flihp** [comment]
Nope. The only thing that is specific to the simulator is **when** `startup` is called. For a physical TPM your firmware / early boot stuff sends the `startup` command. Since the simulator isn't integrated with the firmware it never receives the command.

The `tabrmd` issues the startup command regardless of the TCTI in use since sending this command has no effect if the device / simulator has already received a startup. You get an non-success RC back but it's harmless.

All that said the only time the tools would **need** to issue the startup command is when they're talking to the simulator directly, though sending this command to the TPM under other circumstances will not cause any harm (just extra overhead).

Could be something you bury down in the socket TCTI initialization code?

**Comment by williamcroberts** [comment]
I am thinking, if startup needs to be sent for direct hardware communication as well, then I would want to bury this in the main() prior to execute_tool() and just send it and ignore the harmless return code. What is the harmless return code?

**Comment by flihp** [comment]
The startup tool handles this RC: https://github.com/01org/tpm2.0-tools/blob/master/tools/tpm2_startup.c#L144 (not saying it's right, just that it works). In the spec you're looking for part 3 section 9.3.1.
