### ISSUE TITLE
tpm2_verifysignature fail (0x2cb)

### ISSUE THREAD

**Issue by dandantx** [01org/tpm2.0-tools#65]
tpm2_verifysignature fail with error coed 0x2cb when load a key context created by tpm2_loadexternal.

> tpm2_verifysignature -c context_loadexternal_out_6  -g 0x000B -m secret.data  -s sign.f1 -t tickt_verify_sign.out
contextKeyFile = context_loadexternal_out_6
halg = 0x000b
VerifySignature: using the input signature file as sig structure!
TPM2_VerifySignature TESTS:
VerifySignature: computing message hash succeeded!
msgHash(hex type):
26 34 c3 09 7f 98 e3 68 65 f0 c5 72 00 9c 4f fd 73 31 6b c8 b8 8c cf e8 d1 96 af 35 f4 6e 23 94
tpm2_verifysignature failed, error code: 0x2cb

**Comment by gwei3** [comment]
This is not a bug. 0x2cb means TPM_RC_HANDLE, reported in HMAC signing case while the loaded key doesn't have private portion loaded. Updated the test_tpm2_verifysignature.sh test script to create RSA(0x1) signing key instead of keyedhash (0x8) signing key so that loading only public portion with loadexternal case can be tested properly.
