### ISSUE TITLE
tpm2_nvreadlock fail (Error:0x282)

### ISSUE THREAD

**Issue by dandantx** [01org/tpm2.0-tools#69]
new tool tpm2_nvreadlock fail both on simulator and PTT tpm, as below:

> tpm2_nvread -x 0x1500018 -a 0x40000001 -s 32 -o 0
The size of data:32
 64  6a  38  36  30  43  44  0a  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff

>  tpm2_nvreadlock -x 0x1500018 -a 0x40000001
Failed to lock NVRAM area at index 0x1500018 (22020120).Error:0x282

**Comment by asws** [comment]
use this https://sourceforge.net/projects/ibmtpm20tss/

**Comment by gwei3** [comment]
This is not a issue. This is caused by not setting TPMA_NV_READ_STCLEAR bit when define the NV index. The correct steps of trying nvreadlock are like below:
1. define nv index with TPMA_NV_READ_STCLEAR bit(0x80000000) set
  tpm2_nvdefine -x 0x1500018 -a 0x40000001 -s 32 -t 0x8002000A
2. write content into this nv index
3. lock
  tpm2_nvreadlock -x 0x1500018 -a 0x40000001
